version: 0.2
phases:
  install:
    commands:
      - npm install
      - cd app
      - npm install
      - cd ..
  pre_build:
    commands:
      - npm test # && cd app && npm test; cd ..
  build:
    commands:
      - bash codebuild/build.sh
  post_build:
    commands:
      - bash codebuild/post_build.sh
