version: 0.2
phases:
  install:
    commands:
      - bash scripts/install.sh
  pre_build:
    commands:
      - bash scripts/test.sh
  build:
    commands:
      - bash scripts/build.sh
  post_build:
    commands:
      - bash scripts/post_build.sh
