version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless && npm install
  build:
    commands:
      - serverless deploy -v
  post_build:
    commands:
      - node api/users/populateUsers.js
