version: 0.2
phases:
  # npm install for all our packages
  install:
    commands:
      - npm install -g npm serverless
      - bash scripts/install.sh

  # run tests
  pre_build:
    commands:
      - bash scripts/test.sh

  # checks for master branch, then runs
  build:
    commands:
      - bash scripts/codebuild-deploy.sh
