version: 0.2
phases:
  # npm install for all our packages
  install:
    commands:
      - bash scripts/install.sh
  # run tests
  pre_build:
    commands:
      - bash scripts/test.sh
  # if master, build and deploy
  build:
    commands:
      - bash scripts/codebuild-deploy.sh
