version: 0.2
phases:
  install:
    commands:
      - npm install && cd app && npm install && cd ..
  build:
    commands:
      - bash scripts/build.sh
  post_build:
    commands:
      - bash scripts/post_build.sh
