version: 0.2
phases:
  # npm install for all our packages
  install:
    commands:
      - apt-get update -y
      - apt-get install jq -y
      - bash scripts/install.sh
  # run tests
  pre_build:
    commands:
      - bash scripts/test.sh
  # if master, build and deploy
  build:
    commands:
      - bash scripts/codebuild-deploy.sh
