version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless
      - npm install
      - cd app && npm install && cd ..
  build:
    commands:
      - serverless deploy -v
  post_build:
    commands:
      - node api/users/populate.js
