version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless && serverless fullInstall
  build:
    commands:
      - serverless build && serverless fullDeploy
  post_build:
    commands:
      - node ./api/users/populate.js
