service: serverless-socket

provider:
  name: aws
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - ec2:*
      Resource: "*"

resources:
  Resources:
    socketServer:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: us-east-1a
        ImageId: ami-04681a1dbd79675a5
        InstanceType: t2.micro
        KeyName: serverless-task-notification
        SubnetId: subnet-7d85680b
        SecurityGroupIds:
          - sg-0066d03d410946d76
        Tags:
          - Key: Name
            Value: socketServer
