service: serverless-app

plugins:
  - serverless-finch
  - serverless-plugin-scripts

custom:
  client:
    bucketName: serverless-app-ui
    distributionFolder: build
    errorDocument: index.html

  scripts:
    hooks:
      'package:createDeploymentArtifacts': npm run build
      'deploy:finalize': serverless client deploy --no-confirm

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment:
    REACT_APP_USERS_API:
      "Fn::ImportValue": "UsersAPI"
    REACT_APP_TASKS_API:
      "Fn::ImportValue": "TasksAPI"
    REACT_APP_SOCKET_DNS:
      "Fn::ImportValue": "SocketDNS"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'
