service: serverless-app

plugins:
  - serverless-finch
  - serverless-plugin-scripts

custom:
  client:
    bucketName: serverless-app-ui
    distributionFolder: build
    errorDocument: index.html

  scripts:
    hooks:
      'deploy:finalize': serverless client deploy --no-confirm

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'
