service: serverless-tasks

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - sns:*
      Resource: '*'
  environment:
    TOPIC: arn:aws:sns:us-east-1:#{AWS::AccountId}
    TABLENAME: tasks

functions:
  getTasks:
    handler: getAll.handler
    events:
      - http:
          path: tasks
          method: get
          cors: true
  createTask:
    handler: create.handler
    events:
      - http:
          path: tasks
          method: post
          cors: true
  deleteTask:
    handler: delete.handler
    events:
      - http:
          path: tasks/{id}
          method: delete
          cors: true
  updateTask:
    handler: update.handler
    events:
      - sns: taskComplete

resources:
  Outputs:
    TasksAPI:
      Description: URL for the tasks service
      Export:
        Name: TasksAPI
      Value:
        Fn::Join:
          - ''
          - - 'https://'
            - Ref: ApiGatewayRestApi
            - '.execute-api.us-east-1.amazonaws.com/dev/tasks'
