service: serverless-users

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*'
  environment:
    TABLENAME: users

functions:
  getUsers:
    handler: getAll.handler
    events:
      - http:
          path: users
          method: get
          cors: true

resources:
  Outputs:
    UsersAPI:
      Description: URL for the users service
      Export:
        Name: UsersAPI
      Value:
        Fn::Join:
          - ''
          - - 'https://'
            - Ref: ApiGatewayRestApi
            - '.execute-api.us-east-1.amazonaws.com/dev/users'
