service: serverless-users

plugins:
  - serverless-plugin-scripts
custom:
  scripts:
    hooks:
      "deploy:finalize": node populate.js

functions:
  getUsers:
    handler: getAll.handler
    events:
      - http:
          path: users
          method: get
          cors: true
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: "*"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  Outputs:
    UsersAPI:
      Description: URL for the users service
      Export:
        Name: UsersAPI
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.us-east-1.amazonaws.com/dev/users"
